# Generated by Django 4.2.2 on 2023-10-02 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetails',
            old_name='Product',
            new_name='product',
        ),
    ]
