# Generated by Django 4.2.2 on 2023-10-13 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_payment_shipment_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='shipment_address',
            new_name='ship_address',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='shipment_phone',
            new_name='ship_phone',
        ),
    ]
