# Generated by Django 4.2.2 on 2023-10-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_shipment_address_payment_ship_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='ship_phone',
        ),
    ]
