# Generated by Django 4.2.2 on 2023-10-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_payment_ship_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='shipment_phone',
            field=models.CharField(default='', max_length=11),
        ),
    ]
