# Generated by Django 4.2.2 on 2023-10-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_payment_shipment_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='shipment_phone',
        ),
    ]
