# Generated by Django 4.2.2 on 2023-10-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_payment_shipment_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='ship_address',
            new_name='shipment_address',
        ),
        migrations.AddField(
            model_name='payment',
            name='shipment_phone',
            field=models.CharField(default='01272501297', max_length=50),
        ),
    ]
