# Generated by Django 4.2.2 on 2023-10-13 16:49

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_ship_address_payment_shipment_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='shipment_phone',
            field=creditcards.models.CardNumberField(max_length=25),
        ),
    ]
