# Generated by Django 4.2.2 on 2023-10-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_payment_shipment_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='shipment_phone',
            field=models.CharField(max_length=11),
        ),
    ]
