# Generated by Django 4.2.2 on 2023-10-13 19:04

import creditcards.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_payment_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_number',
            field=creditcards.models.CardNumberField(max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expire',
            field=creditcards.models.CardExpiryField(validators=[django.core.validators.RegexValidator(message='Enter a valid card number (e.g., 1111 2222 3333 4444)', regex='^\\d{4} \\d{4} \\d{4} \\d{4}$')]),
        ),
    ]
