# Generated by Django 4.2.2 on 2023-10-16 19:01

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_payment_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expire',
            field=creditcards.models.CardExpiryField(),
        ),
    ]
